# SPDX-FileCopyrightText: 2026 q0f7
# SPDX-License-Identifier: Apache-2.0
"""Every source and config file Verdra writes starts with its SPDX header (plan 3.2, CLAUDE.md).

Covered: code, config and the assets that can hold a comment (SVG, the message catalogue).
Not covered, each for a reason: Markdown documents (prose, not source), JSON (no comments),
`.python-version` (one line read by tools), binary files, the lockfile (generated by uv) and the
Lucide icons (third-party, ISC, with their own licence file).
"""

import subprocess
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parent.parent
SUFFIXES = {".py", ".toml", ".yml", ".yaml", ".spec", ".svg", ".ts", ".sh", ".ps1", ".iss"}
NAMES = {".gitignore", ".gitattributes", ".editorconfig"}
THIRD_PARTY = (PurePosixPath("src/verdra/assets/icons/lucide"),)
COPYRIGHT = "SPDX-FileCopyrightText: 2026 q0f7"
LICENSE = "SPDX-License-Identifier: Apache-2.0"


def tracked() -> list[PurePosixPath]:
    listed = subprocess.run(
        ["git", "ls-files"],  # noqa: S607 - git from PATH, as in every checkout
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    return [PurePosixPath(name) for name in listed]


def needs_header(path: PurePosixPath) -> bool:
    if any(path.is_relative_to(folder) for folder in THIRD_PARTY):
        return False
    return path.suffix in SUFFIXES or path.name in NAMES


#: The copyright holder's former name (plan 16.2, 5 October 2026): it may not appear anywhere.
FORMER_HOLDER = "The Verdra " + "Authors"


def missing_header(text: str) -> bool:
    head = "\n".join(text.splitlines()[:5])
    return COPYRIGHT not in head or LICENSE not in head


def test_every_source_file_has_its_spdx_header() -> None:
    missing = [
        str(path)
        for path in tracked()
        if needs_header(path)
        and (ROOT / path).exists()
        and missing_header((ROOT / path).read_text(encoding="utf-8"))
    ]
    assert missing == []


def test_the_check_sees_a_missing_header() -> None:
    assert missing_header('<svg xmlns="http://www.w3.org/2000/svg"></svg>\n')
    assert not missing_header(f"<!-- {COPYRIGHT} -->\n<!-- {LICENSE} -->\n<svg/>\n")
    assert needs_header(PurePosixPath("src/verdra/assets/icons/custom/leaf.svg"))
    assert not needs_header(PurePosixPath("src/verdra/assets/icons/lucide/leaf.svg"))
    assert missing_header(f"# SPDX-FileCopyrightText: 2026 {FORMER_HOLDER}\n# {LICENSE}\n")


def test_the_former_holder_name_appears_nowhere() -> None:
    """Plan 16.2: the copyright holder is q0f7 in NOTICE, every header and every text."""
    found = [
        str(path)
        for path in tracked()
        if (ROOT / path).is_file()
        and path.suffix not in {".png", ".ico", ".icns", ".ttf", ".otf", ".woff2", ".qm"}
        and FORMER_HOLDER in (ROOT / path).read_text(encoding="utf-8", errors="replace")
    ]
    assert found == []
    assert "Copyright 2026 q0f7\n" in (ROOT / "NOTICE").read_text(encoding="utf-8")
    assert "Original project: https://github.com/verdra-1/verdra\n" in (ROOT / "NOTICE").read_text(
        encoding="utf-8"
    )
